# ============================================================================
#                    RUNEGRAM - Configuración del Juego
# ============================================================================
#
# Este archivo contiene todas las configuraciones de comportamiento del juego
# que NO son credenciales sensibles. Puede estar en Git y ser modificado por
# administradores sin editar código Python.
#
# IMPORTANTE: Para credenciales sensibles (tokens, passwords), usar .env

# --- Sistema de Presencia (Online/Offline) ---
[online]
# Tiempo de inactividad (en minutos) antes de marcar jugador como offline
threshold_minutes = 5

# TTL en Redis para el timestamp last_seen (en días)
last_seen_ttl_days = 7

# TTL en Redis para el flag offline_notified (en días)
offline_notified_ttl_days = 1

# --- Sistema de Pulse Global ---
[pulse]
# Intervalo del pulse en segundos (cada cuántos segundos ejecuta un tick)
# IMPORTANTE: Cambiar este valor afecta la conversión de ticks a tiempo real
# en todos los scripts que usan interval_ticks
interval_seconds = 2

# --- Paginación ---
[pagination]
# Items por página para comandos con paginación automática
# Aplica a: /inventario, /quien, /items, /personajes, /listarsalas, /listaritems, etc.
items_per_page = 3

# --- Límites de Visualización (solo para comandos con truncado) ---
# Estos valores aplican SOLO a comandos que muestran previsualizaciones
# y tienen alternativas dedicadas para ver listados completos
[display_limits]
# Máximo de items mostrados en /mirar (sala) antes de truncar
# (el jugador puede usar /items para ver listado completo con paginación)
max_room_items = 10

# Máximo de personajes mostrados en /mirar (sala)
# (el jugador puede usar /personajes para ver listado completo con paginación)
max_room_characters = 10

# --- Validación de Personajes ---
[characters]
# Longitud mínima del nombre de personaje
name_min_length = 3

# Longitud máxima del nombre de personaje
# Decisión: usar 15 (del FSM moderno) como estándar para mejor UX móvil
name_max_length = 15

# --- Sistema de Baneos y Moderación ---
[moderation]
# Canal donde se envían notificaciones de apelaciones de ban
# Si se deja vacío (""), las notificaciones se envían directamente a todos los admins
# Debe ser una key válida de CHANNEL_PROTOTYPES (ej: "moderacion", "sistema")
ban_appeal_channel = "moderacion"

# Longitud máxima de la razón del ban (en caracteres)
ban_reason_max_length = 500

# Longitud máxima del texto de apelación (en caracteres)
appeal_max_length = 1000

# Longitud del fragmento de apelación mostrado en notificaciones (en caracteres)
appeal_preview_length = 100

# Items por página en el listado de cuentas baneadas
# Valor menor que pagination.items_per_page para listas críticas de moderación
banned_accounts_per_page = 10

# --- Gameplay General ---
[gameplay]
# Habilitar modo debug (logs extra, comandos de testing)
debug_mode = false
