# alembic/script.py.mako

"""Añadir capacidad de contenedor a los items

Revision ID: 5c4d38b0f409
Revises: d1b407d64b9b
Create Date: 2025-10-01 14:00:11.616518+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c4d38b0f409'
down_revision = 'd1b407d64b9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('parent_item_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_items_parent_item_id_items', 'items', 'items', ['parent_item_id'], ['id'])
    # --- Las líneas que borran apscheduler_jobs han sido eliminadas de aquí ---
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_items_parent_item_id_items', 'items', type_='foreignkey')
    op.drop_column('items', 'parent_item_id')
    # --- Las líneas que recrean apscheduler_jobs han sido eliminadas de aquí ---
    # ### end Alembic commands ###