"""Añadir columna de estado a las cuentas

Revision ID: abe6da21ae81
Revises: f17a871c68a1
Create Date: <LA FECHA SE GENERA AUTOMÁTICamente>

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe6da21ae81'
down_revision = 'f17a871c68a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False))
    # NOTA: Se han eliminado las líneas autogeneradas que intentaban
    # borrar la tabla 'apscheduler_jobs', ya que esa tabla es gestionada
    # por otra migración y no por los modelos de la aplicación.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'status')
    # NOTA: Se han eliminado las líneas autogeneradas que intentaban
    # recrear la tabla 'apscheduler_jobs' en el downgrade.
    # ### end Alembic commands ###